on: ["push", "pull_request"]

name: Run CI Tests

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      MAINNET_RPC: ${{ secrets.mainnet_rpc }}
      KOVAN_RPC: ${{ secrets.kovan_rpc }}
      # increasing available memory for node reduces issues with ganache crashing
      # https://nodejs.org/api/cli.html#cli_max_old_space_size_size_in_megabytes
      NODE_OPTIONS: --max_old_space_size=4096
    services:
      ganache:
        image: trufflesuite/ganache-cli:v6.12.2
        ports:
          - 8545:8545
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install yarn dependencies
        run: yarn

      - name: Check prettier
        run: yarn prettier:check

      - name: Run test #1
        run: npx hardhat test test/admin-test.js

      - name: Run test #2
        run: npx hardhat test test/sale-test.js
        
      - name: Run test #3
        run: npx hardhat test test/staking-test.js
        
      - name: Run test #4
        run: npx hardhat test test/token-sale.test.js
